sudo: required
services:
  - docker
language: generic
compiler:
  - gcc
notifications:
  email:
    on_failure: always
    recipients:
      - 130s@2000.jukuin.keio.ac.jp
env:
  matrix:
    - ROS_DISTRO="noetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu USE_DEB=true
    - ROS_DISTRO="noetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros-testing/ubuntu USE_DEB=true VERBOSE_OUTPUT='true'
    - ROS_DISTRO="noetic" PRERELEASE=true
matrix:
  allow_failures:
    - ROS_DISTRO="noetic" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu USE_DEB=true
    - ROS_DISTRO="noetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
